# Site settings
author: Brenden Thornton
title: Come Code with Me
header-img: img/home-bg.png
email: thorntonbrenden@gmail.com
copyright_name: Brenden Thornton
description: > # this means to ignore newlines until "baseurl:"
  An Autobiography
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bthornton505

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
